### ISSUE TITLE
Number of branches

### ISSUE THREAD

**Issue by hdrdavies** [daUnicorns/BlogSite#22]
Hi guys! Just a note, once you've merged a pull request, you can delete the branch you merged. Helps keep things simple!

**Comment by ltoshea** [comment]
Thanks, these have now been deleted.

**Comment by hdrdavies** [comment]
@ltoshea just a note on issue closing etiquette, it's normally up to the person who opened the issue to close it, so just @ them like this @hdrdavies. Next time! :smile:
