### ISSUE TITLE
Absolutely love the flipping pictures

### ISSUE THREAD

**Issue by hdrdavies** [daUnicorns/BlogSite#24]
That's all I had to say.

**Comment by jay-meister** [comment]
Seems like clicking Liams picture has effect on social buttons. 

We are also big fans of the pics.

**Comment by Virginie-T** [comment]
@JMurphyWeb  I was testing some js code on Liam's picture. Thanks for pointing that out. I fixed it.

**Comment by jay-meister** [comment]
@Virginie-T doesnt seem fixed on gh-pages. let me know when it is
