### ISSUE TITLE
Use descriptive file names

### ISSUE THREAD

**Issue by katbow** [daUnicorns/BlogSite#26]
'useful-stuff.html' is not very descriptive so the purpose is unclear without further investigation.

**Comment by RobStallion** [comment]
@katbow This was just of a dummy page. We will probably end up making it a contact us page in the future. I will change the name to this now. Thanks

**Comment by ltoshea** [comment]
Has now been changed to http://daunicorns.github.io/contact.html
Which has been added as an enhancement.

**Comment by katbow** [comment]
great, thanks.
