### ISSUE TITLE
Images hosted on other pages

### ISSUE THREAD

**Issue by Danwhy** [daUnicorns/BlogSite#35]
It's not a good idea to have all of your images on a separate site. It'll be faster and safer to store the images in your repo.

**Comment by ltoshea** [comment]
I disagree with this and would say that it's bad practice to have loads of media in your github repo. Would love to chat more about this. @Danwhy

**Comment by Danwhy** [comment]
If you have a lot of media to store, then you definitely shouldn't upload it to github. In that case I'd use something like [Amazon S3](https://aws.amazon.com/s3/) for storage. 

But personally, if it's just the assets for a website I find it a lot simpler to just store them in a file in the repo.

It's pretty much just personal preference though. If you'd rather keep your assets and your code separate, that's perfectly valid. I'd just make sure you were hosting them somewhere you have control over.

**Comment by ltoshea** [comment]
Thanks Danwhy will definitely bear that in mind.
