### ISSUE TITLE
Clicking Liam's picture causes overlap

### ISSUE THREAD

**Issue by otajor** [daUnicorns/BlogSite#39]
<img width="368" alt="screen shot 2016-01-22 at 11 16 40" src="https://cloud.githubusercontent.com/assets/13705650/12509349/bf86e5c8-c0f9-11e5-88fa-3217534ce016.png">

This happens when I click Liam's picture (doesn't happen with the others..) - the social media icons jump up so they are under the picture. Not sure why this is.

**Comment by Virginie-T** [comment]
@oturnermajor  I was testing some js code on Liam's picture. Thanks for pointing that out. I fixed it.

**Comment by otajor** [comment]
:+1:
