### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by samhstn** [daUnicorns/BlogSite#43]
Perhapse consider having notes in your javascript to explain what each of the functions do, I don't understand the point of the function slide()? Maybe clarify next to it what this does.

Also I think you should only have one script tag in the index page

**Comment by ltoshea** [comment]
We need the second script tag to actually run the javascript function otherwise it doesn't work. @shouston3

**Comment by ltoshea** [comment]
@shouston3 we've had a bit of a nightmare and had to move repos so it's going to be complicated to show you the commit - our mistake. I'm going to go ahead and close this now the JS is commented.

**Comment by samhstn** [comment]
No worries
